name: Medium article syncer
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-articles:
    name: Update this repo's README with 9ssi7's latest stories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.2.5
        with:
          comment_tag_name: "ARTICLES"
          feed_list: "https://medium.com/feed/@9ssi7"
